// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Reboot Router', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {

      var webdriver = require('selenium-webdriver'),
      var chrome    = require('selenium-webdriver/chrome')

      var options   = new chrome.Options();
      options.addArguments('--headless');

    driver = await new Builder().forBrowser('chrome').withCapabilities(options).build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Reboot Router', async function() {
    await driver.set('Authorization', `Basic ${process.env.USER}:${process.env.PASS}`).get("http://10.1.0.1/start.htm")
    await driver.manage().window().setRect({ width: 1920, height: 1168 })
    await driver.findElement(By.css("#AdvanceTab > span")).click()
    await driver.switchTo().frame(1)
    await driver.findElement(By.id("reboot")).click()
    assert(await driver.switchTo().alert().getText() == "Rebooting the router will disrupt active traffic on the network. Are you sure?")
    await driver.switchTo().alert().accept()
  })
})
